
asm (
     ".global unwind_trampoline \n"
     "unwind_trampoline: \n"
     ".cfi_startproc \n"
     "movq %rsp, %rsi \n"
     ".cfi_def_cfa rsi, 8 \n"
     "pushq %rbp \n"
     ".cfi_offset rbp, -16 \n"
     "pushq %rbx \n"
     "pushq %r12 \n"
     "pushq %r13 \n"
     "pushq %r14 \n"
     "pushq %r15 \n"
     "movq %rsp, %rdx \n"
     "subq $0x08, %rsp \n"
     ".cfi_def_cfa rsp, 0x40 \n"
     "call unwind_recorder \n"
     "addq $0x38, %rsp \n"
     ".cfi_def_cfa rsp, 8 \n"
     "ret \n"
     ".cfi_endproc"
     );

asm (
     ".global unwind_lander \n"
     "unwind_lander: \n"
     "movq %rdi, %rsp \n"
     "popq %rax \n"
     "popq %rbx \n"
     "popq %rcx \n"
     "popq %rdx \n"
     "popq %rdi \n"
     "popq %rsi \n"
     "popq %rbp \n"
     "popq %r8 \n"
     "popq %r9 \n"
     "popq %r10 \n"
     "popq %r11 \n"
     "popq %r12 \n"
     "popq %r13 \n"
     "popq %r14 \n"
     "popq %r15 \n"
     "movq 0(%rsp), %rsp \n"
     "ret \n" // HYPERSPACE JUMP :D
     );
